spring:
  datasource:
      url: jdbc:mysql://localhost:3306/drug?serverTimezone=GMT%2B8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8880

